title: ale.today
# email: hello@ale.today
description: "a small life log"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title/

# Build settings
markdown: kramdown

theme: minima
show_excerpts: true
author: Ale Muñoz
copyright: "Made with 🍊 by Ale Muñoz"

minima:
  skin: orange
  social_links:
    twitter: bomberstudios
    github: bomberstudios

plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
