title: ale, today
email: hello@ale.today
description: 'a small life log'
url: 'https://ale.today'
permalink: /:title

# Build settings
markdown: kramdown

# Defaults
defaults:
  - scope:
      path: '' # an empty string here means all files in the project
      type: 'posts' # previously `post` in Jekyll 2.2.
    values:
      layout: 'post'

show_excerpts: false
author:
  name: Ale Muñoz
  email: hello@ale.today
  twitter: bomberstudios
twitter: bomberstudios
copyright: 'Made with 🍊 by Ale Muñoz'

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag

header_pages:
  - about.md

paginate: 10
paginate_path: "/page/:num/"

include:
  - '.well-known'
  - '_redirects'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
