title: ale.today
email: hello@ale.today
description: >- # this means to ignore newlines until "baseurl:"
  a life log
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  bomberstudios
permalink: /:title/

# Build settings
markdown: kramdown

date_format: "%-d %B %Y"
read_time: true
words_per_minute: 200
twitter:
  username: bomberstudios
author:
  name: Ale Muñoz
  twitter: bomberstudios
  picture: /images/avatar.png

copyright: "Made with 🍊 by Ale Muñoz"

plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
